[versions]
java = "11"
javaLatest = "19"
kotlin = "1.8.21"
kotlinDokka = "1.8.10"
kodeinDI = "7.20.1"
koinDI= "3.4.0"

jackson = "2.15.0"

guice = "5.1.0"
cdi = "3.0.0"
weld = "3.1.0.Final"
weldCore = "4.0.3.Final"

hocon = "1.4.2"
aws = "2.20.55"
jgit = "6.5.0.202303070854-r"

eddsa = "0.3.0"

junit5 = "5.9.3"
assertJ = "3.24.2"
mockito = "5.2.0"
mockk = "1.13.5"
koTestAssertions = "5.6.1"
awsMock = "2.11.0"

errorprone = "2.18.0"
errorpronejavac = "9+181-r4173-1"
detekt = "1.22.0"
gradleDetekt = "1.22.0"

checkStyle = "10.7.0"
pmd = "6.54.0"

jmh = "1.36"
gradleJmh = "0.7.1"

gestalt = "0.20.5"

gradleVersions = "0.46.0"
gitVersions = "2.0.0"
gradleErrorProne = "3.0.1"

[libraries]
kotlin-Reflection = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-dokka = { module = "org.jetbrains.dokka:kotlin-as-java-plugin", version.ref = "kotlin" }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "kotlinDokka" }
kodein-DI = { module = "org.kodein.di:kodein-di-jvm", version.ref = "kodeinDI" }
koin-DI = { module = "io.insert-koin:koin-core", version.ref = "koinDI" }


jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-dataformat-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }

jackson-java8 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jdk8", version.ref = "jackson" }
jackson-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }

jackson-toml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-toml", version.ref = "jackson" }
jackson-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }

guice = { module = "com.google.inject:guice", version.ref = "guice"}

cdi = { module = "jakarta.enterprise:jakarta.enterprise.cdi-api", version.ref = "cdi" }
weld-junit5 = { module  = "org.jboss.weld:weld-junit5", version.ref = "weld" }
weld-core = { module  = "org.jboss.weld:weld-core-impl", version.ref = "weldCore" }

hocon = { module = "com.typesafe:config", version.ref = "hocon" }

aws-S3 = { module = "software.amazon.awssdk:s3", version.ref = "aws" }

jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit" }
jgit-apache-SSH = { module = "org.eclipse.jgit:org.eclipse.jgit.ssh.apache", version.ref = "jgit" }
eddsa = { module = "net.i2p.crypto:eddsa", version.ref = "eddsa" }

junitAPI = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junitEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
assertJ = { module = "org.assertj:assertj-core", version.ref = "assertJ" }

mockito = { module = "org.mockito:mockito-inline", version.ref = "mockito" }

mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
koTestAssertions = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "koTestAssertions" }
aws-Mock = { module = "com.adobe.testing:s3mock-junit5", version.ref = "awsMock" }

jmh = { module = "org.openjdk.jmh:jmh-core", version.ref = "jmh" }
jmh-annotations = { module = "org.openjdk.jmh:jmh-generator-annprocess", version.ref = "jmh" }

errorProne = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone" }
detekt = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
gradle-detekt  = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "gradleDetekt" }

gradle-ben-manes-versions = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "gradleVersions" }
gradle-error-prone = { module = "net.ltgt.gradle:gradle-errorprone-plugin", version.ref = "gradleErrorProne" }
gradle-git-versions = { module = "com.palantir.gradle.gitversion:gradle-git-version", version.ref = "gitVersions" }


gestalt-core = { module = "com.github.gestalt-config:gestalt-core", version.ref = "gestalt" }
gestalt-guice = { module = "com.github.gestalt-config:gestalt-guice", version.ref = "gestalt" }
gestalt-hocon = { module = "com.github.gestalt-config:gestalt-hocon", version.ref = "gestalt" }
gestalt-kotlin = { module = "com.github.gestalt-config:gestalt-kotlin", version.ref = "gestalt" }
gestalt-json = { module = "com.github.gestalt-config:gestalt-json", version.ref = "gestalt" }
gestalt-toml = { module = "com.github.gestalt-config:gestalt-toml", version.ref = "gestalt" }
gestalt-yaml = { module = "com.github.gestalt-config:gestalt-yaml", version.ref = "gestalt" }
gestalt-s3 = { module = "com.github.gestalt-config:gestalt-s3", version.ref = "gestalt" }
gestalt-kodein-di = { module = "com.github.gestalt-config:gestalt-kodein-di", version.ref = "gestalt" }
gestalt-koin-di = { module = "com.github.gestalt-config:gestalt-koin-di", version.ref = "gestalt" }

[bundles]
jackson = ["jackson-core", "jackson-databind", "jackson-dataformat-yaml", "jackson-java8", "jackson-jsr310"]

[plugins]
jmh = { id = "me.champeau.jmh", version.ref = "gradleJmh" }

