---
db:
  hosts:
    - url: jdbc:postgresql://dev.host.name1:5432/mydb
    - url: jdbc:postgresql://dev.host.name2:5432/mydb
    - url: jdbc:postgresql://dev.host.name3:5432/mydb
  connectionTimeout: 600
http:
  pool:
    maxTotal: 1000
    maxPerRoute: 50
admin:
  user: Peter, Kim, Steve
  overrideEnabled: true
