[db]
connectionTimeout = 600

[[db.hosts]]
url = "jdbc:postgresql://dev.host.name1:5432/mydb"

[[db.hosts]]
url = "jdbc:postgresql://dev.host.name2:5432/mydb"

[[db.hosts]]
url = "jdbc:postgresql://dev.host.name3:5432/mydb"

[http.pool]
maxTotal = 1_000
maxPerRoute = 50

[admin]
user = "Peter, Kim, Steve"
overrideEnabled = true
